"""
Agent Service
Orchestrates CrewAI financial agents and processes Pixpoc data
"""

import json
import sys
import os
from typing import Dict, Any
from pathlib import Path
from loguru import logger

# Add finance_bot to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))


class AgentService:
    """Service for managing AI agent execution"""
    
    async def run_comprehensive_planning(
        self, 
        analysis_data: Dict[str, Any]
    ) -> str:
        """
        Execute Comprehensive Planning Agent (Financial + Tax).
        
        Args:
            analysis_data: Raw analysis data from Pixpoc (no parsing needed)
            
        Returns:
            Markdown report from agent
        """
        try:
            logger.info(f"Starting Comprehensive Planning Agent")
            logger.info(f"Analysis data keys: {list(analysis_data.keys())}")
            
            # Import here to avoid circular dependencies
            try:
                from finance_bot.comprehensive_planning.main import ComprehensivePlanningCrew
                
                # Pass raw analysis data - agents will understand JSON dynamically
                crew = ComprehensivePlanningCrew(analysis_data)
                result = crew.run()
                
                logger.info(f"Comprehensive Planning Agent completed successfully")
                return str(result)
                
            except ImportError as e:
                logger.error(f"CrewAI agents not available: {e}")
                raise Exception(f"Agent import failed: {e}")
                
        except Exception as e:
            logger.error(f"Comprehensive Planning Agent failed: {e}")
            return self._generate_error_report(analysis_data, str(e))
    
    def _generate_error_report(self, analysis_data: Dict[str, Any], error_msg: str = "") -> str:
        """Generate error message when agent fails"""
        
        return f"""# ⚠️ Report Generation Issue

## Analysis Could Not Be Completed

We encountered an issue while generating your detailed financial plan.

**Reason:** The AI financial planning agent could not process your data at this time.

**Error Details:** {error_msg}

### Analysis Data Received:
```json
{json.dumps(analysis_data, indent=2)}
```

Please try again later or contact support.

---
*Generated by FinanceBot System*
"""
    
    async def process_call_and_generate_report(
        self, 
        pixpoc_data: Dict[str, Any],
        agent_type: str = "comprehensive_planning"
    ) -> str:
        """
        Process Pixpoc call data and generate report using AI agents.
        
        Args:
            pixpoc_data: Raw data from Pixpoc (analysis callback)
            agent_type: Type of agent to run (default: comprehensive_planning)
            
        Returns:
            Markdown report from agent
        """
        try:
            logger.info(f"Processing with agent type: {agent_type}")
            
            # Run comprehensive planning (financial + tax)
            report = await self.run_comprehensive_planning(pixpoc_data)
            
            return report
            
        except Exception as e:
            logger.error(f"Agent processing failed: {e}")
            raise
