"""
Report Service
Handles report generation, PDF conversion, and storage
"""

import os
import uuid
from datetime import datetime
from typing import Dict, Any
from pathlib import Path
from loguru import logger

import markdown


class ReportService:
    """Service for managing report generation and storage"""
    
    def __init__(self, storage_path: str):
        """
        Initialize report service.
        
        Args:
            storage_path: Base path for report storage
        """
        self.storage_path = Path(storage_path)
        self.storage_path.mkdir(parents=True, exist_ok=True)
    
    def get_user_reports_dir(self, phone_number: str) -> Path:
        """
        Get or create user-specific reports directory.
        
        Args:
            phone_number: User's phone number
            
        Returns:
            Path to user's reports directory
        """
        user_dir = self.storage_path / phone_number
        user_dir.mkdir(parents=True, exist_ok=True)
        return user_dir
    
    def markdown_to_html(self, markdown_content: str, title: str = "Financial Report") -> str:
        """
        Convert Markdown to styled HTML.
        
        Args:
            markdown_content: Markdown text
            title: Report title
            
        Returns:
            HTML string
        """
        # Convert markdown to HTML
        html_content = markdown.markdown(
            markdown_content,
            extensions=['tables', 'fenced_code', 'nl2br']
        )
        
        # Create styled HTML document
        html_template = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>{title}</title>
            <style>
                body {{
                    font-family: 'Arial', 'Helvetica', sans-serif;
                    line-height: 1.6;
                    color: #333;
                    max-width: 800px;
                    margin: 0 auto;
                    padding: 20px;
                }}
                h1 {{
                    color: #2563eb;
                    border-bottom: 3px solid #2563eb;
                    padding-bottom: 10px;
                }}
                h2 {{
                    color: #1e40af;
                    margin-top: 25px;
                }}
                h3 {{
                    color: #1e3a8a;
                }}
                table {{
                    width: 100%;
                    border-collapse: collapse;
                    margin: 15px 0;
                }}
                th, td {{
                    padding: 10px;
                    border: 1px solid #ddd;
                    text-align: left;
                }}
                th {{
                    background-color: #f3f4f6;
                    font-weight: bold;
                }}
                code {{
                    background-color: #f3f4f6;
                    padding: 2px 6px;
                    border-radius: 3px;
                }}
                ul, ol {{
                    margin: 10px 0;
                    padding-left: 30px;
                }}
                .header {{
                    text-align: center;
                    margin-bottom: 30px;
                    padding-bottom: 20px;
                    border-bottom: 2px solid #e5e7eb;
                }}
                .footer {{
                    margin-top: 40px;
                    padding-top: 20px;
                    border-top: 2px solid #e5e7eb;
                    text-align: center;
                    color: #6b7280;
                    font-size: 0.9em;
                }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>🏦 FinanceBot</h1>
                <p>{title} | Generated on {datetime.now().strftime('%B %d, %Y')}</p>
            </div>
            {html_content}
            <div class="footer">
                <p>This report is generated by FinanceBot AI Financial Advisory Platform</p>
                <p>For questions, please contact support@financebot.com</p>
            </div>
        </body>
        </html>
        """
        
        return html_template
    
    def markdown_to_pdf(self, markdown_content: str, output_path: Path, title: str = "Financial Report") -> Path:
        """
        Convert Markdown to PDF (simplified - saves as HTML for now).
        
        Args:
            markdown_content: Markdown text
            output_path: Path to save PDF
            title: Report title
            
        Returns:
            Path to generated file
        """
        try:
            # Generate HTML
            html_content = self.markdown_to_html(markdown_content, title)
            
            # For now, save as HTML (PDF generation requires WeasyPrint which has dependencies)
            # In production, uncomment the PDF generation below
            html_path = output_path.with_suffix('.html')
            with open(html_path, 'w', encoding='utf-8') as f:
                f.write(html_content)
            
            logger.info(f"Report generated: {html_path}")
            
            # Optional: Try PDF generation if weasyprint is available
            try:
                from weasyprint import HTML
                HTML(string=html_content).write_pdf(output_path)
                logger.info(f"PDF generated: {output_path}")
                return output_path
            except ImportError:
                logger.warning("WeasyPrint not available, using HTML format")
                return html_path
            except Exception as e:
                logger.warning(f"PDF generation failed: {e}, using HTML")
                return html_path
                
        except Exception as e:
            logger.error(f"Failed to generate report: {e}")
            raise
    
    async def save_report(
        self,
        phone_number: str,
        report_content: str,
        report_type: str,
        call_id: str
    ) -> Dict[str, Any]:
        """
        Save markdown report and convert to PDF/HTML.
        
        Args:
            phone_number: User's phone number
            report_content: Markdown report content
            report_type: Type of report ('financial_planning', 'tax_planning')
            call_id: Associated call ID
            
        Returns:
            Report metadata
        """
        try:
            # Create user directory
            user_dir = self.get_user_reports_dir(phone_number)
            
            # Generate filenames
            timestamp = datetime.now().strftime('%Y-%m-%d_%H%M%S')
            report_id = str(uuid.uuid4())
            
            md_filename = f"{report_type}_{timestamp}.md"
            pdf_filename = f"{report_type}_{timestamp}.pdf"
            
            md_path = user_dir / md_filename
            pdf_path = user_dir / pdf_filename
            
            # Save markdown
            with open(md_path, 'w', encoding='utf-8') as f:
                f.write(report_content)
            logger.info(f"Markdown saved: {md_path}")
            
            # Convert to PDF/HTML
            title_map = {
                "financial_planning": "Financial Planning Report",
                "tax_planning": "Tax Planning Report"
            }
            actual_file = self.markdown_to_pdf(
                report_content, 
                pdf_path, 
                title=title_map.get(report_type, "Financial Report")
            )
            
            # Get file size
            file_size = os.path.getsize(actual_file)
            
            # Return metadata
            metadata = {
                "id": report_id,
                "type": report_type,
                "phone_number": phone_number,
                "call_id": call_id,
                "md_filename": md_filename,
                "pdf_filename": actual_file.name,
                "md_path": str(md_path),
                "pdf_path": str(actual_file),
                "file_size": file_size,
                "created_at": datetime.now().isoformat()
            }
            
            logger.info(f"Report saved successfully: {report_id}")
            return metadata
        except Exception as e:
            logger.error(f"Failed to save report: {e}")
            raise
